//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public byte[] Password { get; set; }
        public string LastIP { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int LoginCounter { get; set; }
    }
}
