//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefValue
    {
        public int ID { get; set; }
        public string ValueCode { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Description { get; set; }
        public byte TypeID { get; set; }
        public Nullable<byte> Order { get; set; }
        public string CssClass { get; set; }
        public bool IsActive { get; set; }
    }
}
