//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopDBEntities : DbContext
    {
        public ShopDBEntities()
            : base("name=ShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AccountType> AccountTypes { get; set; }
        public DbSet<Listing> Listings { get; set; }
        public DbSet<ListingImage> ListingImages { get; set; }
        public DbSet<ListingImageDeleted> ListingImageDeleteds { get; set; }
        public DbSet<RefType> RefTypes { get; set; }
        public DbSet<RefValue> RefValues { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<RegionZone> RegionZones { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<RefCategory> RefCategories { get; set; }
    }
}
